[package]
name = "dcl"
version = "0.1.0"
edition = "2021"
default-run = "2dcl"

[[bin]]
name = "2dcl"
path = "src/main.rs"

[dependencies]
log = "0.4"
compiler = { path = "../compiler" }
clap = { version = "4.0.17", features = ["derive"] }
tempdir = "0.3"
