[avatar]
ambient_light = true
ambient_light_brightness = 0.1
ambient_light_r = 0.25
ambient_light_g = 0.25
ambient_light_b = 0.25

[world]
starting_parcel_x = 0
starting_parcel_y = 0
min_render_distance = 4
max_render_distance = 7
camera_size = 1.0

[player]
speed = 400.0
scale = 1.0
collider_size_x = 18.0
collider_size_y = 20.0