// This file is generated by rust-protobuf 3.1.0. Do not edit
// .proto file is parsed by protoc --rust-out=...
// @generated

// https://github.com/rust-lang/rust-clippy/issues/702
#![allow(unknown_lints)]
#![allow(clippy::all)]

#![allow(unused_attributes)]
#![cfg_attr(rustfmt, rustfmt::skip)]

#![allow(box_pointers)]
#![allow(dead_code)]
#![allow(missing_docs)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(trivial_casts)]
#![allow(unused_results)]
#![allow(unused_mut)]

//! Generated file from `renderer-protocol/RendererProtocol.proto`

/// Generated files are compatible only with the same version
/// of protobuf runtime.
const _PROTOBUF_VERSION_CHECK: () = ::protobuf::VERSION_3_1_0;

#[derive(PartialEq,Clone,Default,Debug)]
// @@protoc_insertion_point(message:CRDTManyMessages)
pub struct CRDTManyMessages {
    // message fields
    // @@protoc_insertion_point(field:CRDTManyMessages.sceneId)
    pub sceneId: ::std::string::String,
    // @@protoc_insertion_point(field:CRDTManyMessages.payload)
    pub payload: ::std::vec::Vec<u8>,
    // special fields
    // @@protoc_insertion_point(special_field:CRDTManyMessages.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a CRDTManyMessages {
    fn default() -> &'a CRDTManyMessages {
        <CRDTManyMessages as ::protobuf::Message>::default_instance()
    }
}

impl CRDTManyMessages {
    pub fn new() -> CRDTManyMessages {
        ::std::default::Default::default()
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(2);
        let mut oneofs = ::std::vec::Vec::with_capacity(0);
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "sceneId",
            |m: &CRDTManyMessages| { &m.sceneId },
            |m: &mut CRDTManyMessages| { &mut m.sceneId },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "payload",
            |m: &CRDTManyMessages| { &m.payload },
            |m: &mut CRDTManyMessages| { &mut m.payload },
        ));
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<CRDTManyMessages>(
            "CRDTManyMessages",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for CRDTManyMessages {
    const NAME: &'static str = "CRDTManyMessages";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                10 => {
                    self.sceneId = is.read_string()?;
                },
                18 => {
                    self.payload = is.read_bytes()?;
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        if !self.sceneId.is_empty() {
            my_size += ::protobuf::rt::string_size(1, &self.sceneId);
        }
        if !self.payload.is_empty() {
            my_size += ::protobuf::rt::bytes_size(2, &self.payload);
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        if !self.sceneId.is_empty() {
            os.write_string(1, &self.sceneId)?;
        }
        if !self.payload.is_empty() {
            os.write_bytes(2, &self.payload)?;
        }
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> CRDTManyMessages {
        CRDTManyMessages::new()
    }

    fn clear(&mut self) {
        self.sceneId.clear();
        self.payload.clear();
        self.special_fields.clear();
    }

    fn default_instance() -> &'static CRDTManyMessages {
        static instance: CRDTManyMessages = CRDTManyMessages {
            sceneId: ::std::string::String::new(),
            payload: ::std::vec::Vec::new(),
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for CRDTManyMessages {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("CRDTManyMessages").unwrap()).clone()
    }
}

impl ::std::fmt::Display for CRDTManyMessages {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for CRDTManyMessages {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

#[derive(PartialEq,Clone,Default,Debug)]
// @@protoc_insertion_point(message:CRDTResponse)
pub struct CRDTResponse {
    // special fields
    // @@protoc_insertion_point(special_field:CRDTResponse.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a CRDTResponse {
    fn default() -> &'a CRDTResponse {
        <CRDTResponse as ::protobuf::Message>::default_instance()
    }
}

impl CRDTResponse {
    pub fn new() -> CRDTResponse {
        ::std::default::Default::default()
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(0);
        let mut oneofs = ::std::vec::Vec::with_capacity(0);
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<CRDTResponse>(
            "CRDTResponse",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for CRDTResponse {
    const NAME: &'static str = "CRDTResponse";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> CRDTResponse {
        CRDTResponse::new()
    }

    fn clear(&mut self) {
        self.special_fields.clear();
    }

    fn default_instance() -> &'static CRDTResponse {
        static instance: CRDTResponse = CRDTResponse {
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for CRDTResponse {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("CRDTResponse").unwrap()).clone()
    }
}

impl ::std::fmt::Display for CRDTResponse {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for CRDTResponse {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

#[derive(PartialEq,Clone,Default,Debug)]
// @@protoc_insertion_point(message:PullCRDTRequest)
pub struct PullCRDTRequest {
    // message fields
    // @@protoc_insertion_point(field:PullCRDTRequest.sceneId)
    pub sceneId: ::std::string::String,
    // special fields
    // @@protoc_insertion_point(special_field:PullCRDTRequest.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a PullCRDTRequest {
    fn default() -> &'a PullCRDTRequest {
        <PullCRDTRequest as ::protobuf::Message>::default_instance()
    }
}

impl PullCRDTRequest {
    pub fn new() -> PullCRDTRequest {
        ::std::default::Default::default()
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(1);
        let mut oneofs = ::std::vec::Vec::with_capacity(0);
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "sceneId",
            |m: &PullCRDTRequest| { &m.sceneId },
            |m: &mut PullCRDTRequest| { &mut m.sceneId },
        ));
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<PullCRDTRequest>(
            "PullCRDTRequest",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for PullCRDTRequest {
    const NAME: &'static str = "PullCRDTRequest";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                10 => {
                    self.sceneId = is.read_string()?;
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        if !self.sceneId.is_empty() {
            my_size += ::protobuf::rt::string_size(1, &self.sceneId);
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        if !self.sceneId.is_empty() {
            os.write_string(1, &self.sceneId)?;
        }
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> PullCRDTRequest {
        PullCRDTRequest::new()
    }

    fn clear(&mut self) {
        self.sceneId.clear();
        self.special_fields.clear();
    }

    fn default_instance() -> &'static PullCRDTRequest {
        static instance: PullCRDTRequest = PullCRDTRequest {
            sceneId: ::std::string::String::new(),
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for PullCRDTRequest {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("PullCRDTRequest").unwrap()).clone()
    }
}

impl ::std::fmt::Display for PullCRDTRequest {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for PullCRDTRequest {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

///  CRDTStreamRequest is deprecated
#[derive(PartialEq,Clone,Default,Debug)]
// @@protoc_insertion_point(message:CRDTStreamRequest)
pub struct CRDTStreamRequest {
    // special fields
    // @@protoc_insertion_point(special_field:CRDTStreamRequest.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a CRDTStreamRequest {
    fn default() -> &'a CRDTStreamRequest {
        <CRDTStreamRequest as ::protobuf::Message>::default_instance()
    }
}

impl CRDTStreamRequest {
    pub fn new() -> CRDTStreamRequest {
        ::std::default::Default::default()
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(0);
        let mut oneofs = ::std::vec::Vec::with_capacity(0);
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<CRDTStreamRequest>(
            "CRDTStreamRequest",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for CRDTStreamRequest {
    const NAME: &'static str = "CRDTStreamRequest";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> CRDTStreamRequest {
        CRDTStreamRequest::new()
    }

    fn clear(&mut self) {
        self.special_fields.clear();
    }

    fn default_instance() -> &'static CRDTStreamRequest {
        static instance: CRDTStreamRequest = CRDTStreamRequest {
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for CRDTStreamRequest {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("CRDTStreamRequest").unwrap()).clone()
    }
}

impl ::std::fmt::Display for CRDTStreamRequest {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for CRDTStreamRequest {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

static file_descriptor_proto_data: &'static [u8] = b"\
    \n(renderer-protocol/RendererProtocol.proto\"F\n\x10CRDTManyMessages\x12\
    \x18\n\x07sceneId\x18\x01\x20\x01(\tR\x07sceneId\x12\x18\n\x07payload\
    \x18\x02\x20\x01(\x0cR\x07payload\"\x0e\n\x0cCRDTResponse\"+\n\x0fPullCR\
    DTRequest\x12\x18\n\x07sceneId\x18\x01\x20\x01(\tR\x07sceneId\"\x17\n\
    \x11CRDTStreamRequest:\x02\x18\x012\xb5\x01\n\x0bCRDTService\x12.\n\x08S\
    endCrdt\x12\x11.CRDTManyMessages\x1a\r.CRDTResponse\"\0\x121\n\x08PullCr\
    dt\x12\x10.PullCRDTRequest\x1a\x11.CRDTManyMessages\"\0\x12C\n\x16CrdtNo\
    tificationStream\x12\x12.CRDTStreamRequest\x1a\x11.CRDTManyMessages\"\00\
    \x01J\xc5\x04\n\x06\x12\x04\0\0\x17\x01\n\x08\n\x01\x0c\x12\x03\0\0\x12\
    \n\n\n\x02\x04\0\x12\x04\x02\0\x05\x01\n\n\n\x03\x04\0\x01\x12\x03\x02\
    \x08\x18\n\x0b\n\x04\x04\0\x02\0\x12\x03\x03\x02\x15\n\x0c\n\x05\x04\0\
    \x02\0\x05\x12\x03\x03\x02\x08\n\x0c\n\x05\x04\0\x02\0\x01\x12\x03\x03\t\
    \x10\n\x0c\n\x05\x04\0\x02\0\x03\x12\x03\x03\x13\x14\n\x0b\n\x04\x04\0\
    \x02\x01\x12\x03\x04\x02\x14\n\x0c\n\x05\x04\0\x02\x01\x05\x12\x03\x04\
    \x02\x07\n\x0c\n\x05\x04\0\x02\x01\x01\x12\x03\x04\x08\x0f\n\x0c\n\x05\
    \x04\0\x02\x01\x03\x12\x03\x04\x12\x13\n\t\n\x02\x04\x01\x12\x03\x07\0\
    \x17\n\n\n\x03\x04\x01\x01\x12\x03\x07\x08\x14\n\n\n\x02\x04\x02\x12\x04\
    \t\0\x0b\x01\n\n\n\x03\x04\x02\x01\x12\x03\t\x08\x17\n\x0b\n\x04\x04\x02\
    \x02\0\x12\x03\n\x02\x15\n\x0c\n\x05\x04\x02\x02\0\x05\x12\x03\n\x02\x08\
    \n\x0c\n\x05\x04\x02\x02\0\x01\x12\x03\n\t\x10\n\x0c\n\x05\x04\x02\x02\0\
    \x03\x12\x03\n\x13\x14\n-\n\x02\x04\x03\x12\x04\x0e\0\x10\x01\x1a!\x20CR\
    DTStreamRequest\x20is\x20deprecated\n\n\n\n\x03\x04\x03\x01\x12\x03\x0e\
    \x08\x19\n\n\n\x03\x04\x03\x07\x12\x03\x0f\x02\x1b\n\x0b\n\x04\x04\x03\
    \x07\x03\x12\x03\x0f\x02\x1b\n\n\n\x02\x06\0\x12\x04\x12\0\x17\x01\n\n\n\
    \x03\x06\0\x01\x12\x03\x12\x08\x13\n\x0b\n\x04\x06\0\x02\0\x12\x03\x13\
    \x029\n\x0c\n\x05\x06\0\x02\0\x01\x12\x03\x13\x06\x0e\n\x0c\n\x05\x06\0\
    \x02\0\x02\x12\x03\x13\x0f\x1f\n\x0c\n\x05\x06\0\x02\0\x03\x12\x03\x13*6\
    \n\x0b\n\x04\x06\0\x02\x01\x12\x03\x14\x02=\n\x0c\n\x05\x06\0\x02\x01\
    \x01\x12\x03\x14\x06\x0e\n\x0c\n\x05\x06\0\x02\x01\x02\x12\x03\x14\x0f\
    \x1e\n\x0c\n\x05\x06\0\x02\x01\x03\x12\x03\x14)9\n3\n\x04\x06\0\x02\x02\
    \x12\x03\x16\x02T\x1a&\x20CrdtNotificationStream\x20is\x20deprecated\n\n\
    \x0c\n\x05\x06\0\x02\x02\x01\x12\x03\x16\x06\x1c\n\x0c\n\x05\x06\0\x02\
    \x02\x02\x12\x03\x16\x1d.\n\x0c\n\x05\x06\0\x02\x02\x06\x12\x03\x169?\n\
    \x0c\n\x05\x06\0\x02\x02\x03\x12\x03\x16@Pb\x06proto3\
";

/// `FileDescriptorProto` object which was a source for this generated file
fn file_descriptor_proto() -> &'static ::protobuf::descriptor::FileDescriptorProto {
    static file_descriptor_proto_lazy: ::protobuf::rt::Lazy<::protobuf::descriptor::FileDescriptorProto> = ::protobuf::rt::Lazy::new();
    file_descriptor_proto_lazy.get(|| {
        ::protobuf::Message::parse_from_bytes(file_descriptor_proto_data).unwrap()
    })
}

/// `FileDescriptor` object which allows dynamic access to files
pub fn file_descriptor() -> &'static ::protobuf::reflect::FileDescriptor {
    static generated_file_descriptor_lazy: ::protobuf::rt::Lazy<::protobuf::reflect::GeneratedFileDescriptor> = ::protobuf::rt::Lazy::new();
    static file_descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::FileDescriptor> = ::protobuf::rt::Lazy::new();
    file_descriptor.get(|| {
        let generated_file_descriptor = generated_file_descriptor_lazy.get(|| {
            let mut deps = ::std::vec::Vec::with_capacity(0);
            let mut messages = ::std::vec::Vec::with_capacity(4);
            messages.push(CRDTManyMessages::generated_message_descriptor_data());
            messages.push(CRDTResponse::generated_message_descriptor_data());
            messages.push(PullCRDTRequest::generated_message_descriptor_data());
            messages.push(CRDTStreamRequest::generated_message_descriptor_data());
            let mut enums = ::std::vec::Vec::with_capacity(0);
            ::protobuf::reflect::GeneratedFileDescriptor::new_generated(
                file_descriptor_proto(),
                deps,
                messages,
                enums,
            )
        });
        ::protobuf::reflect::FileDescriptor::new_generated_2(generated_file_descriptor)
    })
}
