on: 
  pull_request:
  push:
    branches:
      - main

name: Build

jobs:
  build:
    name: Release Build
    strategy:
      matrix:
        os: [windows-latest, ubuntu-22.04, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: sudo apt-get update; sudo apt-get install --no-install-recommends libasound2-dev libudev-dev libgtk-3-dev libjavascriptcoregtk-4.0-dev libsoup2.4-dev libjavascriptcoregtk-4.0-dev libgdk3.0-cil-dev libgdk-pixbuf-2.0-dev libpango1.0-dev libwebkit2gtk-4.0-dev
        if: runner.os == 'linux'
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release
